<a href="https://colab.research.google.com/github/eduswiss/deep-learning-with-tensorflow/blob/master/notebooks/10_regression_in_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regression Example in TensorFlow

Predicting house prices in Boston, Massachusetts

## Load dependencies

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing # new!
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout 
from tensorflow.keras.layers import BatchNormalization 
from tensorflow.keras.callbacks import ModelCheckpoint # new!
import os # new!

## Load data

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

## Design neural network architecture

In [7]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                448       
_________________________________________________________________
batch_normalization (BatchNo (None, 32)                128       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_1 (Batch (None, 16)                64        
_________________________________________________________________
dropout (Dropout)            (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
Total params: 1,185
Trainable params: 1,089
Non-trainable params: 96
_____________________________________________________

## Configure Model

In [9]:
model.compile(loss='mean_squared_error', optimizer='nadam')

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [13]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', # decimal integers
                                  save_weights_only=True)

## Train!

In [14]:
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid),
          callbacks=[modelcheckpoint]) # val loss below 50 is good, 40 great

Epoch 1/32
51/51 [==============================] - 0s 5ms/step - loss: 581.6971 - val_loss: 690.8627
Epoch 2/32
51/51 [==============================] - 0s 2ms/step - loss: 566.4902 - val_loss: 646.2505
Epoch 3/32
51/51 [==============================] - 0s 2ms/step - loss: 546.8816 - val_loss: 614.1396
Epoch 4/32
51/51 [==============================] - 0s 2ms/step - loss: 530.0147 - val_loss: 558.1592
Epoch 5/32
51/51 [==============================] - 0s 2ms/step - loss: 500.3141 - val_loss: 525.2509
Epoch 6/32
51/51 [==============================] - 0s 2ms/step - loss: 472.6334 - val_loss: 510.0638
Epoch 7/32
51/51 [==============================] - 0s 2ms/step - loss: 437.7386 - val_loss: 499.3825
Epoch 8/32
51/51 [==============================] - 0s 2ms/step - loss: 397.9904 - val_loss: 516.3551
Epoch 9/32
51/51 [==============================] - 0s 2ms/step - loss: 357.6762 - val_loss: 527.5195
Epoch 10/32
51/51 [==============================] - 0s 2ms/step - loss: 313.9005 

## Performing inference

In [15]:
model.load_weights(output_path + '/weights.28.hdf5')

In [16]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [17]:
y_valid[42]

14.1

In [18]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[13.389759]], dtype=float32)